name: SmartlifeIntegration
author: Twasi-Team
main: net.twasiplugin.smartlife.SmartlifeIntegration
dependency: true
version: "1.0"
api: |
  type SmartlifeIntegration {
    authenticationUri: String,
    control: SmartlifeIntegrationControl
  }

  type SmartlifeIntegrationControl {
    devices: [TuyaDevice],
    scenes(homeId: Long): [TuyaScene],
    homes: [TuyaHome],
    triggerScene(homeId: Long, sceneId: String): PanelResult
  }

  type TuyaDeviceStatus {
    code: String,
    value: String
  }

  type TuyaDevice {
    id: String,
    uid: String,
    category: String,
    productId: String,
    sub: Boolean,
    online: Boolean,
    name: String,
    ip: String,
    timeZone: String,
    createTime: String,
    updateTime: String,
    activeTime: String,
    status: [TuyaDeviceStatus]
  }
  
  type TuyaHome {
    homeId: Long,
    name: String
  }

  type TuyaScene {
    sceneId: String,
    name: String,
    background: String
  }

  type TuyaSceneAction {
    entityId: String,
    executorProperty: String,
    actionExecutor: String
  }