name: SmartlifeIntegration
author: Twasi-Team
main: net.twasidependency.smartlife.SmartlifeIntegration
dependency: true
version: "1.0"
api: |
  type SmartlifeIntegration {
    authenticationUri: String,
    maxSequenceSteps: Int,
    control: SmartlifeIntegrationControl,
    disconnect: PanelResult
  }

  type SmartlifeIntegrationControl {
    devices: [TuyaDevice],
    scenes(homeId: Long): [TuyaScene],
    homes: [TuyaHome],
    triggerScene(homeId: Long, sceneId: String): PanelResult,
    sceneSequences: SceneSequences
  }

  type TuyaDeviceStatus {
    code: String,
    value: String
  }

  type TuyaDevice {
    id: String,
    uid: String,
    category: String,
    productId: String,
    sub: Boolean,
    online: Boolean,
    name: String,
    ip: String,
    timeZone: String,
    createTime: String,
    updateTime: String,
    activeTime: String,
    status: [TuyaDeviceStatus]
  }
  
  type TuyaHome {
    homeId: Long,
    name: String
  }

  type TuyaScene {
    sceneId: String,
    name: String,
    background: String
  }

  type TuyaSceneAction {
    entityId: String,
    executorProperty: String,
    actionExecutor: String
  }

  type SceneSequences {
    list: SceneSequencePageable,
    play(id: String): PanelResult,
    delete(id: String): PanelResult,
    create(newSequence: SceneSequenceInput): SceneSequence,
    update(id: String, update: SceneSequenceInput): SceneSequence
  }

  pageable type SceneSequence {
    id: String,
    name: String,
    variable: String,
    updated: Long,
    created: Long,
    steps: [SceneSequenceStep]
  }

  input SceneSequenceInput {
    name: String,
    variable: String,
    steps: [SceneSequenceStepInput]
  }

  type SceneSequenceStep {
    homeId: Long,
    sceneId: String,
    msDelay: Int
  }

  input SceneSequenceStepInput {
      homeId: Long,
      sceneId: String,
      msDelay: Int
    }
